version: '3.3'

services:
  tradingbot_execute_client:
    build: .
    image: tradingbot_execute_client
    container_name: tradingbot_execute_client
    environment:
      - DEBUG=true
    volumes:
      - ./:/home/docker_volume
    working_dir: /home/docker_volume
    entrypoint: tail -f /dev/null
    extra_hosts:
      - "host.docker.internal:host-gateway"

 