version: '3.3'

services:
  tradingbot_execute_client:
    build: .
    image: tradingbot_execute_client
    container_name: tradingbot_execute_client
    volumes:
      - ./:/home/docker_volume
    working_dir: /home/docker_volume
    entrypoint: python run.py

 