version: '3.3'

services:
  tradingbot_execute_client:
    image: wave3snipers/tradingbot_execute_client:latest
    container_name: tradingbot_execute_client
    volumes:
      - ./:/home/docker_volume
    working_dir: /home/docker_volume
    entrypoint: python run.py