name: Deploy to production

on:
  push:
    branches:
      - action

jobs:
  check_dockerfile_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Check if Dockerfile has been modified
      - name: Check for Dockerfile changes
        id: dockerfile_changed
        run: |
          echo "Checking changes between ${{ github.event.before }} and ${{ github.sha }}"
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "Dockerfile" || echo "false")
          if [ "$CHANGED" != "false" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

  build_and_push:
    runs-on: ubuntu-latest
    needs: check_dockerfile_changes
    if: ${{ needs.check_dockerfile_changes.outputs.changed == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build -t wave3snipers/tradingbot_execute_client:latest .
        
      - name: Push Docker image
        run: docker push wave3snipers/tradingbot_execute_client:latest